CREATE TABLE IF NOT EXISTS mpa (
                        mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mpa_name VARCHAR(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS films (
                         film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(40) NOT NULL,
                         description VARCHAR(200),
                         release_date DATE,
                         duration INTEGER,
                         rate INTEGER DEFAULT 0,
                         mpa_id INTEGER REFERENCES mpa (mpa_id)
);
CREATE TABLE IF NOT EXISTS genre(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres(
    film_genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INTEGER REFERENCES genre (genre_id),
    film_id INTEGER REFERENCES films (film_id)
);
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(20) NOT NULL,
    login VARCHAR(20) NOT NULL,
    name VARCHAR(20),
    birthday DATE
);
CREATE TABLE IF NOT EXISTS likes(
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id)
);
CREATE TABLE IF NOT EXISTS friend_status(
  friend_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users (user_id),
  friend_id INTEGER REFERENCES users (user_id),
  status BOOLEAN DEFAULT FALSE NOT NULL
);